services:
  postgres:
    container_name: postgres-budget
    image: postgres
    environment:
      - POSTGRES_DB=budget_tracker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-budget
    restart: unless-stopped

  backend:
    container_name: spring-budget
    build: .
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    environment:
      jwt_secret_key: 7c7bee10f6f24d9a5dd31a74574317ae3a7b0e08536b3f2961c1dc725d377931
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budget_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - spring-budget
    restart: unless-stopped

networks:
  spring-budget:
    driver: bridge

volumes:
  postgres:
    driver: local
